"""add_pet_records_tables

Revision ID: 120c9438cd16
Revises: 9e9ca9b9c9f4
Create Date: 2025-01-16 17:14:56.305965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120c9438cd16'
down_revision: Union[str, None] = '9e9ca9b9c9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 