"""add_reminder_settings

Revision ID: 2954e55da54b
Revises: 120c9438cd16
Create Date: 2025-01-16 17:50:54.617084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2954e55da54b'
down_revision: Union[str, None] = '120c9438cd16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('template_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_templates_id'), 'report_templates', ['id'], unique=False)
    op.create_table('daily_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_observations_id'), 'daily_observations', ['id'], unique=False)
    op.create_table('dewormings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('medicine_name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('next_due_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dewormings_id'), 'dewormings', ['id'], unique=False)
    op.create_table('medical_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_visits_id'), 'medical_visits', ['id'], unique=False)
    op.create_table('reminder_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('reminder_type', sa.String(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=True),
    sa.Column('notification_method', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_settings_id'), 'reminder_settings', ['id'], unique=False)
    op.create_table('report_template_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('changelog', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_template_versions_id'), 'report_template_versions', ['id'], unique=False)
    op.create_table('shared_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('shared_with_id', sa.Integer(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shared_with_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_templates_id'), 'shared_templates', ['id'], unique=False)
    op.add_column('vaccine_records', sa.Column('batch_number', sa.String(), nullable=True))
    op.alter_column('vaccine_records', 'pet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vaccine_records', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('vaccine_records', 'next_due_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('vaccine_records_pet_id_fkey', 'vaccine_records', type_='foreignkey')
    op.create_foreign_key(None, 'vaccine_records', 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
    op.alter_column('weight_records', 'pet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('weight_records', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint('weight_records_pet_id_fkey', 'weight_records', type_='foreignkey')
    op.create_foreign_key(None, 'weight_records', 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weight_records', type_='foreignkey')
    op.create_foreign_key('weight_records_pet_id_fkey', 'weight_records', 'pets', ['pet_id'], ['id'])
    op.alter_column('weight_records', 'date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('weight_records', 'pet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'vaccine_records', type_='foreignkey')
    op.create_foreign_key('vaccine_records_pet_id_fkey', 'vaccine_records', 'pets', ['pet_id'], ['id'])
    op.alter_column('vaccine_records', 'next_due_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('vaccine_records', 'date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('vaccine_records', 'pet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('vaccine_records', 'batch_number')
    op.drop_index(op.f('ix_shared_templates_id'), table_name='shared_templates')
    op.drop_table('shared_templates')
    op.drop_index(op.f('ix_report_template_versions_id'), table_name='report_template_versions')
    op.drop_table('report_template_versions')
    op.drop_index(op.f('ix_reminder_settings_id'), table_name='reminder_settings')
    op.drop_table('reminder_settings')
    op.drop_index(op.f('ix_medical_visits_id'), table_name='medical_visits')
    op.drop_table('medical_visits')
    op.drop_index(op.f('ix_dewormings_id'), table_name='dewormings')
    op.drop_table('dewormings')
    op.drop_index(op.f('ix_daily_observations_id'), table_name='daily_observations')
    op.drop_table('daily_observations')
    op.drop_index(op.f('ix_report_templates_id'), table_name='report_templates')
    op.drop_table('report_templates')
    # ### end Alembic commands ### 