version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=petwell
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"  # 开发环境使用 5432 端口

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data: 