version: '3.8'

services:
  postgres_test:
    image: postgres:15
    environment:
      - POSTGRES_DB=petwell_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"  # Use port 5434 instead

  minio_test:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9002:9000"  # API port changed to 9002
      - "9003:9001"  # Console port changed to 9003
    command: server /data --console-address ":9001"
    volumes:
      - minio_test_data:/data

volumes:
  minio_test_data: 